name: bed12
version: 0.0.1
description: |
  Genomic feature annotations in BED12 format.
tags:
- annotation
- bed
produces: bed
requires:
  assets: []
  files:
  - name: bedgz
    description: Genomic feature annotations in gzipped BED12 format
  tools: []
build:
  command: |
    cp {bedgz} {output_dir}/{genome}.bed.gz
  resources:
    memory: 1GB
    disk: 2GB
    time: 10m
outputs:
- pattern: '*.bed.gz'
  description: BED12 annotation file (gzipped)
test:
  commands:
  - test -f {output_dir}/{genome}.bed.gz
metadata:
  author: nsheff
  created: '2026-05-20'
  license: BSD-2-Clause
