name: fasta_txome
version: 0.0.1
description: |
  cDNA sequences in the FASTA format, indexed FASTA (produced with samtools
  faidx) and chromosome sizes file.
tags:
- reference
- sequence
- transcriptome
requires:
  assets: []
  files:
  - name: fasta
    description: Gzipped FASTA file of transcript sequences
  tools:
  - name: samtools
    version: '>=1.17'
    source: bioconda
build:
  command: |
    cp {fasta} {output_dir}/{genome}.fa.gz
    gzip -df {output_dir}/{genome}.fa.gz
    samtools faidx {output_dir}/{genome}.fa
    cut -f 1,2 {output_dir}/{genome}.fa.fai > {output_dir}/{genome}.chrom.sizes
  resources:
    memory: 4GB
    disk: 10GB
    time: 1h
outputs:
- pattern: '*.fa'
  description: Transcriptome FASTA file
- pattern: '*.fa.fai'
  description: FASTA index file
- pattern: '*.chrom.sizes'
  description: Chromosome sizes file
test:
  commands:
  - test -f {output_dir}/{genome}.fa
  - test -f {output_dir}/{genome}.fa.fai
  - test -f {output_dir}/{genome}.chrom.sizes
metadata:
  author: nsheff
  created: '2026-05-20'
  license: BSD-2-Clause
